name: RT-Extension-ActivityReports
version: 0.1
abstract: RT Extension-ActivityReports Extension
author: Alex Vandiver <alexmv@bestpractical.com>
license: perl
distribution_type: module
requires:
  Time::Duration: 0
no_index:
  directory:
    - html
    - inc
generated_by: Module::Install version 0.41
